name: check_code

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - develop

jobs:
  check:
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: 1.1.13
      - run: "$(dirname $(realpath poetry))/bin/python" -m pip install urllib3==1.26.15
      - run: poetry config virtualenvs.create false
      - run: poetry install --no-interaction --no-ansi
      - run: flake8 .
      - run: mypy more_pathlib

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: 1.1.13
      - run: "$(dirname $(realpath poetry))/bin/python" -m pip install urllib3==1.26.15
      - run: poetry config virtualenvs.create false
      - run: poetry install --no-interaction --no-ansi
      - run: poetry run python -m pytest